pageinfo = [[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null]];
pagedata = [ ["additional_console_commands.htm","Additional console commands","Additional console commands Top Previous Next wayPoints.printWayPointsForCar(carId) - print all points for car. wayPoints.printCurrentCarId() - pr...",""],
["bngs_mode.htm","BeamNG - System Lua Mode","BeamNG - System Lua Mode Top Previous Next Chose it here: ",""],
["creating_paths.htm","Creating paths","Creating paths Top Previous Next 1.Invent a path :) 2.Go to the starting place. 3.In the console ( choose BeamNG - System Lua mode ) invoke the co...",""],
["installation.htm","Installation","Installation Top Previous Next Manual installations 1.Unzip the downloaded archive into the game folder. 2.Open game_folder\\lua\\system\\main.lua an...",""],
["introduction.htm","Introduction","Introduction Top Next Manual version: 1.0.5 For script version: 1.0.7 By Incognito . Forum thread ",""],
["manual.htm","Manual","Manual Top Previous Next ",""],
["ui_app.htm","UI App","UI App Top Previous This mod comes with UI App - WaypointsGUI. That app can handle almost all mod commands. With this app, you no longer need to u...",""],
["using_of_ready_paths.htm","Run car by a path","Run car by a path Top Previous Next 1.Put the car somewhere near the starting point of path (but not too close). 2.Open the console ( choose BeamN...",""],
["welcome_topic.htm","Welcome topic","Welcome topic Top Previous Next This is mod that allows you to run cars by waypoints. Based on simpleAI. You can download it here: http://www.beam...",""]];
